In [3]:
import numpy as np

In [6]:
l1=[1,2,3,4]
l2=[5,6,7,8]

In [7]:
l1+l2

[1, 2, 3, 4, 5, 6, 7, 8]

In [8]:
l2-l1

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [9]:
arr1=np.array(l1)
arr2=np.array(l2)

In [10]:
arr1+arr2

array([ 6,  8, 10, 12])

In [11]:
arr2-arr1

array([4, 4, 4, 4])

In [12]:
type(arr1)

numpy.ndarray

In [13]:
arr1.shape

(4,)

In [25]:
a=np.array([[1,2,3,4]])

In [26]:
a.shape

(1, 4)

In [83]:
b=a.transpose()

In [84]:
b

array([[1],
       [2],
       [3],
       [4]])

In [29]:
a+b

array([[2, 4, 6, 8]])

In [85]:
np.dot(a,b)

array([[30]])

In [86]:
np.sum(a)

10

In [32]:
np.max(a)

4

In [87]:
np.transpose

<function numpy.transpose(a, axes=None)>

In [88]:
np.transpose

<function numpy.transpose(a, axes=None)>

In [89]:
np.T

AttributeError: module 'numpy' has no attribute 'T'

In [90]:
np.reshape(a,(2,2))

array([[1, 2],
       [3, 4]])

In [91]:
np.reshape(a,(1,-1))

array([[1, 2, 3, 4]])

In [50]:
A=np.random.randint(1,70, size=(5,5))


In [51]:
A

array([[34, 57, 56,  9, 20],
       [60,  5, 64, 36, 45],
       [20,  3, 51, 14, 25],
       [66, 41, 46, 34, 26],
       [53, 35, 61, 23, 60]])

In [54]:
A[2,2]

51

In [55]:
A[ 2:5, 2:4]

array([[51, 14],
       [46, 34],
       [61, 23]])

In [56]:
A[ 2, : ]

array([20,  3, 51, 14, 25])

In [63]:
c=A[ 3:5,3:5 ]

In [82]:
c

array([[34, 26],
       [23, 60]])

In [65]:
c.shape

(2, 2)

In [66]:
4+c

array([[38, 30],
       [27, 64]])

In [67]:
2*c

array([[ 68,  52],
       [ 46, 120]])

In [68]:
c**2

array([[1156,  676],
       [ 529, 3600]], dtype=int32)

In [72]:
def distance(j,k):
    return np.sum((k-j)**2)**0.5

In [75]:
j= np.array([5,2])
k=np.array([2,7])

In [76]:
distance(j,k)

5.830951894845301

In [77]:
np.linalg.inv(c)

array([[ 0.04160888, -0.01803051],
       [-0.01595007,  0.02357836]])

In [80]:
c.flatten()

array([34, 26, 23, 60])